In [3]:
from sklearn.feature_extraction.text import CountVectorizer
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt


In [4]:
dados = pd.read_excel('dff.xlsx')


In [9]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(dados)
print(X.toarray())  


[[1 0 1 0 1 0 0 0]
 [0 0 0 0 0 1 1 0]
 [0 1 0 1 0 0 0 1]]
